<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Task;
use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * @param int|null $id
     * @return Task
     */
    public function findOrCreate(int $id = null): Task
    {
        if (null !== $id) {
            /** @var Task $task */
            $task = $this->find($id);

            if (null !== $task) {
                return $task;
            }
        }

        return new Task();
    }
}
